### ISSUE TITLE
[Web] 홈 여행 상세

### ISSUE THREAD

**Issue by Limgabi** [PACKIT-Project/PACKIT-Web#15]
## 📌 Issue
홈 여행 상세

## ✅ Todo
- [x] 여행 조회 (기본)
- [x] 여행 초대 코드 복사
- [x] 여행 조회 바텀 시트
